version: '3.10'

services:

  db:
    image: postgres:14.3-alpine3.15
    ports:
      - "7778:5432"
    environment:
      POSTGRES_USER: app_aio
      POSTGRES_PASSWORD: 5555
      POSTGRES_DB: app_aio
